changelog:
  exclude:
    labels:
      - skip-release-notes
  categories:
    - title: Breaking changes
      labels:
        - breaking-change
    - title: Features
      labels:
        - enhancement
    - title: Fixes
      labels:
        - bug
    - title: Performance
      labels:
        - performance
    - title: Documentation
      labels:
        - documentation
    - title: Maintenance and dependencies
      labels:
        - maintenance
        - dependencies
    - title: Other changes
      labels:
        - "*"
